### ISSUE TITLE
Create the ability to set custom icon for each marker

### ISSUE THREAD

**Issue by deversjkee** [DivanDesign/jQuery.ddMap#1]
Передавать каждой метке свою метку это крутая идея. Надо реализовать когда нибудь. Посмотреть документацию можно тут. https://tech.yandex.ru/maps/doc/jsapi/2.1/dg/concepts/geoobjects-docpage/

**Comment by Ronef** [comment]
3a9a5220a1716551655a5d4ba90a1f9a8f6662bc
